schemas:
  - name: test
    schemaType: DB_IN_ONE_SERVER
    defaultDataNode: dn1
    tables:
      - name: travelrecord
      - name: company
  - name: test2
    schemaType: DB_IN_MULTI_SERVER
    tables:
      - name: travelrecord2
        dataNodes: dn3
  - name: test3
    schemaType: ANNOTATION_ROUTE
    tables:
      - name: travelrecord
        dataNodes: dn1,dn2,dn3,dn4
        type: SHARING_DATABASE
      - name: travelrecord2
        dataNodes: dn1,dn2,dn3
        type: GLOBAL
