defaultSchemaName: test2
schemas:
  - name: test2
    schemaType: DB_IN_MULTI_SERVER
    tables:
      - name: travelrecord
        dataNodes: dn1
      - name: travelrecord2
        dataNodes: dn2
#      - name: company
#  - name: test2
#    schemaType: DB_IN_MULTI_SERVER
#    tables:
#      - name: travelrecord2
#        dataNodes: dn3
#  - name: test3
#    schemaType: ANNOTATION_ROUTE
#    tables:
#      - name: travelrecord
#        dataNodes: dn1,dn2,dn3,dn4
#        message: SHARING_DATABASE

