defaultSchemaName: db12
schemas:
  - name: db12
    schemaType: DB_IN_ONE_SERVER
    defaultDataNode: dn1
  - name: db22
    schemaType: DB_IN_ONE_SERVER
    defaultDataNode: dn1
  - name: test2
    schemaType: DB_IN_MULTI_SERVER
    defaultDataNode: dn1
    tables:
      - name: travelrecord2
        dataNodes: dn2
      - name: travelrecord3
        dataNodes: dn3
  - name: test3
    schemaType: ANNOTATION_ROUTE
    defaultDataNode: dn1
    tables:
      - name: travelrecord
        type: SHARING_DATABASE
        dataNodes: dn1,dn2,dn3
#      - name: company
#  - name: test2
#    schemaType: DB_IN_MULTI_SERVER
#    tables:
#      - name: travelrecord2
#        dataNodes: dn3
#  - name: test3
#    schemaType: ANNOTATION_ROUTE
#    tables:
#      - name: travelrecord
#        dataNodes: dn1,dn2,dn3,dn4
#        message: SHARING_DATABASE

